#define BOOST_TEST_DYN_LINK
#define BOOST_TEST_MODULE JSON_TEST_SUITE_NUMBER_FAILURES
#include <boost/test/unit_test.hpp>

#include "TestParser.h"

JSON_PARSER_EXPECT_FAILURE(n_number_multidigit_then_00,                R"json(  123\0\0  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_0dot1dot2,                         R"json(  [0.1.2]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number__01,                               R"json(  [-01]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_0dot3eplus,                        R"json(  [0.3e+]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_0dot3e,                            R"json(  [0.3e]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_0_capital_Eplus,                   R"json(  [0E+]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_0_capital_E,                       R"json(  [0E]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_0dote1,                            R"json(  [0.e1]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_0eplus,                            R"json(  [0e+]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_0e,                                R"json(  [0e]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_1_000,                             R"json(  [1 000.0]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_1dot0eplus,                        R"json(  [1.0e+]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_1dot0e_,                           R"json(  [1.0e-]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_1dot0e,                            R"json(  [1.0e]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number__1dot0dot,                         R"json(  [-1.0.]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_1eE2,                              R"json(  [1eE2]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_plus1,                             R"json(  [+1]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_dot_1,                             R"json(  [.-1]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_2doteplus3,                        R"json(  [2.e+3]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_2dote_3,                           R"json(  [2.e-3]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_2dote3,                            R"json(  [2.e3]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_dot2e_3,                           R"json(  [.2e-3]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number__2dot,                             R"json(  [-2.]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_9doteplus,                         R"json(  [9.e+]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_expression,                        R"json(  [1+2]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_hex_1_digit,                       R"json(  [0x1]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_hex_2_digits,                      R"json(  [0x42]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_infinity,                          R"json(  [Infinity]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_plusInf,                           R"json(  [+Inf]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_Inf,                               R"json(  [Inf]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_invalidplus_,                      R"json(  [0e+-1]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_invalid_negative_real,             R"json(  [-123.123foo]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_invalid_utf_8_in_bigger_int,       R"json(  [123�]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_invalid_utf_8_in_exponent,         R"json(  [1e1�]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_invalid_utf_8_in_int,              R"json(  [0�]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_plusplus,                          R"json(  [++1234]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_minus_infinity,                    R"json(  [-Infinity]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_minus_sign_with_trailing_garbage,  R"json(  [-foo]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_minus_space_1,                     R"json(  [- 1]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number__NaN,                              R"json(  [-NaN]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_NaN,                               R"json(  [NaN]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_neg_int_starting_with_zero,        R"json(  [-012]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_neg_real_without_int_part,         R"json(  [-.123]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_neg_with_garbage_at_end,           R"json(  [-1x]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_real_garbage_after_e,              R"json(  [1ea]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_real_with_invalid_utf8_after_e,    R"json(  [1e�]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_real_without_fractional_part,      R"json(  [1.]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_starting_with_dot,                 R"json(  [.123]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_UplusFF11_fullwidth_digit_one,     R"json(  [１]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_with_alpha_char,                   R"json(  [1.8011670033376514H-308]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_with_alpha,                        R"json(  [1.2a-3]  )json")
JSON_PARSER_EXPECT_FAILURE(n_number_with_leading_zero,                 R"json(  [012]  )json")
