
#define JSONSTREAM_TRIGGER_DOCUMENT_BEGIN true
#define JSONSTREAM_TRIGGER_DOCUMENT_END true
#define JSONSTREAM_TRIGGER_OBJECT_BEGIN true
#define JSONSTREAM_TRIGGER_OBJECT_END true
#define JSONSTREAM_TRIGGER_OBJECT_EMPTY true
#define JSONSTREAM_TRIGGER_ARRAY_BEGIN true
#define JSONSTREAM_TRIGGER_ARRAY_END true
#define JSONSTREAM_TRIGGER_ARRAY_EMPTY true

#define JSONSTREAM_ONLY_FLOAT_NUMBER false

#define JSONSTREAM_MAX_DEPTH 4
#define JSONSTREAM_BUFFER_LIMIT 100

#define JSONSTREAM_CERR_ERROR_MSG true