
#ifdef JSONSTREAM_TRIGGER_ALL
#   define JSONSTREAM_TRIGGER_DOCUMENT_BEGIN true
#   define JSONSTREAM_TRIGGER_DOCUMENT_END true
#   define JSONSTREAM_TRIGGER_OBJECT_BEGIN true
#   define JSONSTREAM_TRIGGER_OBJECT_END true
#   define JSONSTREAM_TRIGGER_OBJECT_EMPTY true
#   define JSONSTREAM_TRIGGER_ARRAY_BEGIN true
#   define JSONSTREAM_TRIGGER_ARRAY_END true
#   define JSONSTREAM_TRIGGER_ARRAY_EMPTY true
#else
#   ifndef JSONSTREAM_TRIGGER_DOCUMENT_BEGIN
#       define JSONSTREAM_TRIGGER_DOCUMENT_BEGIN false
#   endif
#   ifndef JSONSTREAM_TRIGGER_DOCUMENT_END
#       define JSONSTREAM_TRIGGER_DOCUMENT_END false
#   endif
#   ifndef JSONSTREAM_TRIGGER_OBJECT_BEGIN
#       define JSONSTREAM_TRIGGER_OBJECT_BEGIN false
#   endif
#   ifndef JSONSTREAM_TRIGGER_OBJECT_END
#       define JSONSTREAM_TRIGGER_OBJECT_END false
#   endif
#   ifndef JSONSTREAM_TRIGGER_OBJECT_EMPTY
#       define JSONSTREAM_TRIGGER_OBJECT_EMPTY true
#   endif
#   ifndef JSONSTREAM_TRIGGER_ARRAY_BEGIN
#       define JSONSTREAM_TRIGGER_ARRAY_BEGIN false
#   endif
#   ifndef JSONSTREAM_TRIGGER_ARRAY_END
#       define JSONSTREAM_TRIGGER_ARRAY_END false
#   endif
#   ifndef JSONSTREAM_TRIGGER_ARRAY_EMPTY
#       define JSONSTREAM_TRIGGER_ARRAY_EMPTY true
#   endif
#endif

#ifndef JSONSTREAM_ONLY_FLOAT_NUMBER
#   define JSONSTREAM_ONLY_FLOAT_NUMBER false
#endif

#ifndef JSONSTREAM_MAX_DEPTH
#   define JSONSTREAM_MAX_DEPTH 4
#endif

#ifndef JSONSTREAM_BUFFER_LIMIT
#   define JSONSTREAM_BUFFER_LIMIT 100
#endif
